image: ruby:2.2.2

services:
  - redis:latest
  - postgres:9.4
  - rabbitmq:latest

variables:
  POSTGRES_DB: spacescrape_test
  POSTGRES_USER: postgres
  RABBITMQ_NODENAME: rabbit_test

before_script:
  - gem install bundler
  - bundle install --path /cache/bunder
  - bundle exec rake db:migrate RACK_ENV=test

test:
  script:
    - bundle exec rake test:coverage
