default: &default
  pool: 5
  timeout: 5000
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  username: postgres

development:
  <<: *default
  database: spacescrape_development

test:
  <<: *default
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  database: spacescrape_test

production:
  <<: *default
  database: spacescrape_production
