defaults: &defaults
  amqp: 'amqp://guest:guest@localhost:5672'
  exchange: 'spacescrape.workers'
  exchange_type: direct

development:
  <<: *defaults
  threads: 1
  workers: 1

test:
  <<: *defaults
  amqp: "amqp://guest:guest@<%= ENV['RABBITMQ_NODENAME'] %>:5672"

production:
  <<: *defaults
