defaults: &defaults
  amqp: 'amqp://guest:guest@localhost:5672'

development:
  <<: *defaults
  threads: 1
  workers: 1
  share_threads: true

test:
  <<: *defaults
  amqp: "amqp://guest:guest@<%= ENV['RABBITMQ_NODENAME'] %>:5672"

production:
  <<: *defaults
